# Generated by Django 3.2.15 on 2023-06-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_1', '0002_auto_20230531_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
